_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    authz: {}
    authc:

      openid_auth_domain:
        order: 0

        http_enabled: true
        transport_enabled: false

        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: preferred_username
            roles_key: opensearch_roles
            openid_connect_url: "http://keycloak:8080/realms/test/.well-known/openid-configuration"
        authentication_backend:
          type: noop
